### ISSUE TITLE
TODO: list

### ISSUE THREAD

**Issue by geovanij2** [geovanij2/rust-server#1]
## List of things to implement:
- [ ] Add more documentation to ThreadPool and its public methods.
- [ ] Add tests of the library’s functionality.
- [ ] Change calls to unwrap to more robust error handling.
- [ ] Use ThreadPool to perform some task other than serving web requests.
- [ ] Find a thread pool crate on https://crates.io/ and implement a similar web server using the crate instead. Then compare its API and robustness to the thread pool we implemented.
